# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Archethic < Formula
  desc ""
  homepage "https://github.com/archethic-foundation/archethic-cli"
  version "1.2.1"

  depends_on "git"

  on_macos do
    url "https://github.com/archethic-foundation/archethic-cli/releases/download/v1.2.1/archethic-cli_1.2.1_Darwin_all.tar.gz"
    sha256 "30e01da2fb1e29f098ca1ed334c7ffcaf400332bf34e296be5a0f6b0ea870499"

    def install
      bin.install "archethic-cli"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/archethic-foundation/archethic-cli/releases/download/v1.2.1/archethic-cli_1.2.1_Linux_arm64.tar.gz"
      sha256 "0699868dccbf5e4211b1777e9d940886fdc9b2ae57063990ec57767b1811b2b5"

      def install
        bin.install "archethic"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/archethic-foundation/archethic-cli/releases/download/v1.2.1/archethic-cli_1.2.1_Linux_x86_64.tar.gz"
      sha256 "d63b4bf205124a089b27d722606b6ec1b6b88c8f69d05ac426f133a741cbaf41"

      def install
        bin.install "archethic"
      end
    end
  end
end
